package com.moodsinger.ccrt_clinic.exceptions.enums;

public enum ExceptionErrorCodes {
  USER_NOT_FOUND, BLOG_NOT_FOUND, USER_NOT_CREATED, FIRST_NAME_NOT_VALID, LAST_NAME_NOT_VALID,
  EMAIL_NOT_VALID, PASSWORD_NOT_VALID, REQUIRED_REQUEST_BODY, FORBIDDEN, USER_TYPE_NOT_VALID
}
