package com.moodsinger.ccrt_clinic.exceptions.enums;

public enum MessageCodes {
  USER_NOT_FOUND, BLOG_NOT_FOUND, USER_NOT_CREATED, FIRST_NAME_NOT_VALID, LAST_NAME_NOT_VALID,
  EMAIL_NOT_VALID, PASSWORD_NOT_VALID, REQUIRED_REQUEST_BODY, FORBIDDEN, USER_TYPE_NOT_VALID, MALFORMED_JSON_BODY,
  FILE_SAVE_ERROR, USER_OTP_SERVICE_BLOCKED, OTP_CODE_EXPIRED, OTP_CODE_MISMATCH, DOCTOR_SCHEDULE_CREATION_ERROR,
  USERNAME_PASSWORD_MISMATCH, REQUEST_PENDING_APPROVAL, SLOT_NOT_CREATED, SCHEDULE_NOT_FOUND, OVERLAPPING_SLOT,
  SLOT_NOT_FOUND, APPOINTMENT_NOT_FOUND, APPOINTMENT_VERIFICATION_CODE_MISMATCH, RESOURCE_NOT_FOUND,
  PRESCRIPTION_ALREADY_EXISTS, GENDER_NOT_VALID, BIRTH_DATE_NOT_VALID, SPECIALIZATION_NOT_VALID, EDUCATION_NOT_FOUND,
  TRAINING_NOT_FOUND, EXPERIENCE_NOT_FOUND, AWARD_NOT_FOUND, VALUE_OUT_OF_RANGE, FEE_FIELD_ERROR, REQUEST_NOT_FOUND,
  FEE_CHANGING_REQUEST_CREATION_ERROR, SLOT_BOOKED, PRESCRIPTION_NOT_FOUND, PASSWORD_MISMATCH,
  PASSWORD_RESET_TOKEN_MISMATCH, PASSWORD_UPDATE_SUCCESSFUL, PASSWORD_RESET_SUCCESSFUL
}
